server:
  port: 8080
spring:
  rabbitmq:
    username: battcn
    password: battcn
    host: 192.168.0.133
    port: 5672
    virtual-host: /
    listener:
      simple:
        # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失
        acknowledge-mode: manual
